language: generic

# Need Docker running
sudo: required # Need super user to run docker
services:
  - docker

# Build using Dockerfile.dev
before_install:
  - docker build -t sanjayginde/docker-react -f Dockerfile.dev .

# Run test suite
script:
  - docker run -e CI=true sanjayginde/docker-react npm run test -- --coverage

# Deploy code to AWS
deploy:
  # edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-application"
  env: "docker-react-application-production"
  bucket_name: "elasticbeanstalk-us-east-1-541326117573"
  bucket_path: "docker-react-application"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
