apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: multi-docker
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-docker
      component: web
  template:
    metadata:
      labels:
        app: multi-docker
        component: web
    spec:
      containers:
        - name: client
          image: sanjayginde/multi-docker-client
          ports:
            - containerPort: 3000
