apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050            # Port that another pod and/or container uses to access
      targetPort: 3000      # Container port to open up
      nodePort: 31515       # Port exposed on the actual Node (will be random if not defined)
  selector:                 # Targets metadata labels
    app: multi-docker
    component: web
