# No longer used. Replaced with client-deployment.yaml
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: multi-docker
    component: web
spec:
  containers:
    - name: client
      image: sanjayginde/multi-docker-client
      ports:
        - containerPort: 3000
