version: "3"

services:
  verdaccio:
    # image: verdaccio/verdaccio
    build: .
    ports:
      - 4873:4873
    volumes:
      - verdaccio-storage:/verdaccio/storage

volumes:
  verdaccio-storage:
